import './globals.css'
import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@components/utils/ThemeProvider'
import { SessionProvider } from '@components/utils/SessionProvider'
import Show from '@components/utils/Show'
import Limited from './limited'
import { headers } from 'next/headers'
import { Ratelimit } from '@upstash/ratelimit'
import { kv } from '@vercel/kv'

///
import AuthButton from '@components/visual/Auth/AuthButton'

const rateCache: Map<string, number> = new Map()

const ratelimit = new Ratelimit({
    redis: kv,
    // 5 requests from the same IP in 5 seconds
    limiter: Ratelimit.slidingWindow(5, '10 s'),
    ephemeralCache: rateCache
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default async function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    const ip_address = headers().get('x-forwarded-for')!
    const { success } = await ratelimit.limit(ip_address)

    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthButton onLoggedIn={'goodbay'} onLoggedOut={'hello'} />
                <SessionProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                        enableColorScheme
                    >
                        <Show when={[success]} fallback={<Limited />}>
                            {children}
                        </Show>
                    </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
